import 'package:flutter/material.dart';import 'package:jenson_k_s_application1/core/app_export.dart';import 'package:jenson_k_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:jenson_k_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:jenson_k_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:jenson_k_s_application1/widgets/custom_outlined_button.dart';import 'package:jenson_k_s_application1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AddTripScreen extends StatelessWidget {AddTripScreen({Key? key}) : super(key: key);

TextEditingController editTextController = TextEditingController();

TextEditingController editTextController1 = TextEditingController();

TextEditingController editTextController2 = TextEditingController();

TextEditingController editTextController3 = TextEditingController();

TextEditingController editTextController4 = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildLineNine(context), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 49.v), child: Column(children: [Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 15.v), decoration: AppDecoration.outlineBlack9007.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Trip Details", style: CustomTextStyles.titleLargeArefRuqaaRegular)), _buildTripDetails(context), SizedBox(height: 17.v), _buildDriverName(context), SizedBox(height: 16.v), _buildVehicleNo(context), SizedBox(height: 18.v), _buildTripNo(context), SizedBox(height: 23.v)])), SizedBox(height: 59.v), CustomOutlinedButton(height: 49.v, width: 134.h, text: "Add Trip", buttonTextStyle: CustomTextStyles.titleLargeArefRuqaaRegular, onPressed: () {onTapAddTrip(context);}), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildLineNine(BuildContext context) { return SizedBox(height: 55.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomCenter, child: SizedBox(width: double.maxFinite, child: Divider())), Align(alignment: Alignment.topLeft, child: Container(height: 51.v, width: 58.h, margin: EdgeInsets.only(left: 6.h, top: 1.v), decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1)))), CustomAppBar(leadingWidth: 41.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgShare, margin: EdgeInsets.only(left: 29.h, top: 19.v, bottom: 18.v), onTap: () {onTapShare(context);}), centerTitle: true, title: AppbarSubtitle(text: "Add Trip"), styleType: Style.bgFill_1)])); } 
/// Section Widget
Widget _buildTripDetails(BuildContext context) { return Container(width: 306.h, padding: EdgeInsets.all(6.h), decoration: AppDecoration.outlineBlack9009.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 81.v, width: 271.h, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.topLeft, child: Text("from", style: CustomTextStyles.titleLargeArefRuqaaRegular)), CustomTextFormField(width: 251.h, controller: editTextController, alignment: Alignment.bottomRight, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15, filled: true, fillColor: theme.colorScheme.onPrimaryContainer.withOpacity(1))])), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(right: 19.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 44.v), child: Text("to", style: CustomTextStyles.titleLargeArefRuqaaRegular)), Expanded(child: Padding(padding: EdgeInsets.only(left: 1.h, top: 16.v), child: CustomTextFormField(controller: editTextController1, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15, filled: true, fillColor: theme.colorScheme.onPrimaryContainer.withOpacity(1))))])), SizedBox(height: 28.v)])); } 
/// Section Widget
Widget _buildDriverName(BuildContext context) { return Container(height: 57.v, width: 271.h, margin: EdgeInsets.only(left: 8.h), child: Stack(alignment: Alignment.topLeft, children: [CustomTextFormField(width: 251.h, controller: editTextController2, alignment: Alignment.bottomRight, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15, filled: true, fillColor: theme.colorScheme.onPrimaryContainer.withOpacity(1)), Align(alignment: Alignment.topLeft, child: Text("Driver name", style: CustomTextStyles.titleLargeArefRuqaaRegular))])); } 
/// Section Widget
Widget _buildVehicleNo(BuildContext context) { return Container(height: 57.v, width: 271.h, margin: EdgeInsets.only(left: 8.h), child: Stack(alignment: Alignment.topLeft, children: [CustomTextFormField(width: 251.h, controller: editTextController3, alignment: Alignment.bottomRight, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15, filled: true, fillColor: theme.colorScheme.onPrimaryContainer.withOpacity(1)), Align(alignment: Alignment.topLeft, child: Text("Vehicle No", style: CustomTextStyles.titleLargeArefRuqaaRegular))])); } 
/// Section Widget
Widget _buildTripNo(BuildContext context) { return Container(height: 55.v, width: 273.h, margin: EdgeInsets.only(left: 8.h), child: Stack(alignment: Alignment.topLeft, children: [CustomTextFormField(width: 251.h, controller: editTextController4, textInputAction: TextInputAction.done, alignment: Alignment.bottomRight, borderDecoration: TextFormFieldStyleHelper.outlineBlackTL15, filled: true, fillColor: theme.colorScheme.onPrimaryContainer.withOpacity(1)), Align(alignment: Alignment.topLeft, child: Text("Trip No", style: CustomTextStyles.titleLargeArefRuqaaRegular))])); } 
/// Navigates to the homeoneScreen when the action is triggered.
onTapShare(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeoneScreen); } 
/// Navigates to the addTriptwoScreen when the action is triggered.
onTapAddTrip(BuildContext context) { Navigator.pushNamed(context, AppRoutes.addTriptwoScreen); } 
 }
