import 'package:flutter/material.dart';import 'package:jenson_k_s_application1/core/app_export.dart';import 'package:jenson_k_s_application1/widgets/custom_elevated_button.dart';import 'package:jenson_k_s_application1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AndroidLargeEightScreen extends StatelessWidget {AndroidLargeEightScreen({Key? key}) : super(key: key);

TextEditingController productDescriptionEditTextController = TextEditingController();

TextEditingController fiberLengthvalueEditTextController = TextEditingController();

TextEditingController yieldvalueEditTextController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.deepPurple50, resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 14.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 8.h, right: 16.h), child: Column(children: [_buildCloseRow(context), SizedBox(height: 45.v), _buildProductDescriptionEditText(context), SizedBox(height: 37.v), _buildFiberLengthvalueEditText(context), SizedBox(height: 37.v), _buildArrowUpStack(context, colorLabel: "Crimp"), SizedBox(height: 37.v), _buildArrowUpStack(context, colorLabel: "Color"), SizedBox(height: 37.v), _buildArrowUpStack(context, colorLabel: "Purity"), SizedBox(height: 37.v), _buildArrowUpStack(context, colorLabel: "Breed"), SizedBox(height: 37.v), _buildYieldvalueEditText(context), SizedBox(height: 37.v), _buildArrowUpStack(context, colorLabel: "Processing "), SizedBox(height: 48.v), _buildCalculateButton(context), SizedBox(height: 4.v), Text("as per the BIS Standard(IS 1349)", style: CustomTextStyles.labelLargePrimaryContainer), SizedBox(height: 30.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("Estimated Price", style: CustomTextStyles.titleLargeRegular_1))), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h, right: 42.h), child: Row(children: [Container(height: 36.v, width: 197.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(18.h))), Padding(padding: EdgeInsets.only(left: 19.h, top: 9.v, bottom: 9.v), child: Text("in rupees", style: theme.textTheme.bodyMedium))]))), SizedBox(height: 64.v), Divider(indent: 32.h, endIndent: 22.h)]))))])))); } 
/// Section Widget
Widget _buildCloseRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgCloseBlack900, height: 20.v, width: 24.h, margin: EdgeInsets.only(top: 8.v, bottom: 14.v), onTap: () {onTapImgClose(context);}), Padding(padding: EdgeInsets.only(left: 17.h), child: Text("Quality Calculator", style: CustomTextStyles.displaySmallInter))]); } 
/// Section Widget
Widget _buildProductDescriptionEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 3.h), child: CustomTextFormField(controller: productDescriptionEditTextController, hintText: "Fiber Fitness", hintStyle: theme.textTheme.bodyMedium!, suffix: Padding(padding: EdgeInsets.fromLTRB(30.h, 13.v, 7.h, 10.v), child: Text("in microns", style: TextStyle(color: Color(0XFF000000), fontSize: 12.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400))), suffixConstraints: BoxConstraints(maxHeight: 39.v), contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 10.v))); } 
/// Section Widget
Widget _buildFiberLengthvalueEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 3.h), child: CustomTextFormField(controller: fiberLengthvalueEditTextController, hintText: "Fiber Length", hintStyle: theme.textTheme.bodyMedium!, suffix: Padding(padding: EdgeInsets.fromLTRB(30.h, 12.v, 10.h, 11.v), child: Text("in inches", style: TextStyle(color: Color(0XFF000000), fontSize: 12.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400))), suffixConstraints: BoxConstraints(maxHeight: 39.v), contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 10.v))); } 
/// Section Widget
Widget _buildYieldvalueEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 3.h), child: CustomTextFormField(controller: yieldvalueEditTextController, hintText: "Yield", hintStyle: theme.textTheme.bodyMedium!, textInputAction: TextInputAction.done, suffix: Padding(padding: EdgeInsets.fromLTRB(30.h, 13.v, 9.h, 10.v), child: Text("in kgs ", style: TextStyle(color: Color(0XFF000000), fontSize: 12.fSize, fontFamily: 'Inter', fontWeight: FontWeight.w400))), suffixConstraints: BoxConstraints(maxHeight: 39.v), contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 10.v))); } 
/// Section Widget
Widget _buildCalculateButton(BuildContext context) { return CustomElevatedButton(height: 43.v, width: 208.h, text: "Calculate", buttonStyle: CustomButtonStyles.fillOnPrimaryContainer, buttonTextStyle: CustomTextStyles.headlineSmallRegular); } 
/// Common widget
Widget _buildArrowUpStack(BuildContext context, {required String colorLabel, }) { return SizedBox(height: 39.v, width: 321.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 9.v), decoration: AppDecoration.outlineBlack9001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), CustomImageView(imagePath: ImageConstant.imgArrowup, height: 14.v, width: 26.h)]))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Text(colorLabel, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.black900))))])); } 

/// Navigates back to the previous screen.
onTapImgClose(BuildContext context) { Navigator.pop(context); } 
 }
