import 'package:flutter/material.dart';import 'package:jenson_k_s_application1/core/app_export.dart';import 'package:jenson_k_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:jenson_k_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:jenson_k_s_application1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class LoginScreen extends StatelessWidget {LoginScreen({Key? key}) : super(key: key);

TextEditingController passwordController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 3.v), child: Column(children: [Divider(), SizedBox(height: 82.v), _buildFrameFiftyEight(context), Spacer(), SizedBox(height: 57.v, width: 227.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(height: 55.v, width: 227.h, decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(15.h), border: Border.all(color: appTheme.black900, width: 1.h)))), Align(alignment: Alignment.center, child: Text("Login", style: theme.textTheme.displaySmall))])), SizedBox(height: 55.v), _buildConfirmation(context), SizedBox(height: 36.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 51.v, leadingWidth: 35.h, leading: Container(height: 18.v, width: 12.h, margin: EdgeInsets.only(left: 23.h, top: 23.v, bottom: 10.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgShare, height: 18.v, width: 12.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgShare, height: 18.v, width: 12.h, alignment: Alignment.center)])), centerTitle: true, title: AppbarSubtitle(text: "Login"), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildFrameFiftyEight(BuildContext context) { return Opacity(opacity: 0.5, child: Container(margin: EdgeInsets.symmetric(horizontal: 10.h), padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 87.v), decoration: AppDecoration.outlineBlack9006.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgUser2, height: 30.adaptSize, width: 30.adaptSize, margin: EdgeInsets.only(top: 9.v, bottom: 4.v)), Container(height: 44.v, width: 257.h, margin: EdgeInsets.only(left: 6.h), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 1.v, width: 257.h, margin: EdgeInsets.only(bottom: 5.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 257.h, child: Divider())), Align(alignment: Alignment.center, child: SizedBox(width: 257.h, child: Divider()))]))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("User Id", style: CustomTextStyles.headlineMediumBlack900)))]))]), SizedBox(height: 58.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgPassword1, height: 30.adaptSize, width: 30.adaptSize, margin: EdgeInsets.only(top: 16.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h, bottom: 2.v), child: CustomTextFormField(controller: passwordController, hintText: "Password", hintStyle: CustomTextStyles.headlineMediumBlack900, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, obscureText: true, contentPadding: EdgeInsets.symmetric(horizontal: 7.h))))])]))); } 
/// Section Widget
Widget _buildConfirmation(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 29.h, right: 42.h), child: Row(children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("Don’t have an account?  ", style: CustomTextStyles.titleLargeArefRuqaaRegular)), Container(height: 32.v, width: 73.h, margin: EdgeInsets.only(top: 2.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: GestureDetector(onTap: () {onTapView(context);}, child: Container(height: 26.v, width: 73.h, decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1))))), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapTxtSignup(context);}, child: Text("Signup", style: CustomTextStyles.titleLargeArefRuqaaTeal400)))]))]))); } 
/// Navigates to the roleScreen when the action is triggered.
onTapView(BuildContext context) { Navigator.pushNamed(context, AppRoutes.roleScreen); } 
/// Navigates to the roleScreen when the action is triggered.
onTapTxtSignup(BuildContext context) { Navigator.pushNamed(context, AppRoutes.roleScreen); } 
 }
